### ISSUE TITLE
Connection closed with code 1006 for reason ""

### ISSUE THREAD

**Issue by jeozey** [gegy1000/Slyther#11] opened 2016-10-21 14:11 UTC
Hi,I build your project and run client,
each server can be pin well,
but when play it logs "Connection closed with code 1006 for reason """.
Can you help me? I'am interesting to your Slyther game.
Thank You Very Much!!!

**Comment by Gegy** [comment] 2016-10-21 14:38
Duplicate of #9, I am in the process of trying to fix this.

**Closed as completed by Gegy** 2016-10-21 14:38 UTC
Labels: bug, duplicate
